server:
  port: 8083

spring:
  application:
    name: kafka-basics-demo-consumer

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: kafka-consumer-demo
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.kafka.model
        spring.json.value.default.type: com.kafka.model.Cource